matrix:
  include:
    - language: rust
      python:
        - 3.7
      rust:
        - stable
      install:
        - python3 -m pip install -r requirements.txt
      script:
        - cargo build --verbose
        - cargo test --verbose
