matrix:
  include:
    - language: python
      python: 
        - 3.7
      install: 
        - pip install -r requirements.txt

    - language: rust
      rust:
        - stable
      script:
        - cargo build --verbose
        - cargo test --verbose
