matrix:
  include:
    - language: rust
      rust:
        - stable
      install:
        - pip3 install -r requirements.txt
      script:
        - cargo build --verbose
        - cargo test --verbose
