matrix:
  include:
    - language: rust
      addons:
        apt:
          update: true
          packages:
            - "python3"
            - "python3-pip"
      python:
        - 3.7
      rust:
        - stable
      before_install:
        - sudo pip install --upgrade pip
        - sudo python3 -m pip install -r requirements.txt
      script:
        - cargo build --verbose
        - cargo test --verbose
