matrix:
  include:
    - language: rust
    
      addons:
        apt:
          packages:
            - "python3"
            - "python3-pip"
      rust:
        - stable
      install:
        - python3 -m pip install -r requirements.txt
      script:
        - cargo build --verbose
        - cargo test --verbose
