[package]
name = "gym-rs"
version = "0.1.0"
authors = ["Roberto <rob.ariosa@hotmail.com>"]
edition = "2018"

description = "Open AI environments bindings for Rust"
repository = "https://github.com/MrRobb/gym-rs"
documentation = "https://docs.rs/gym-rs"
readme = "README.md"
keywords = ["openai", "gym", "environments", "reinforcement-learning", "bindings"]
categories = ["api-bindings"]
license = "MIT/Apache-2.0"

[badges]
maintenance = { status = "experimental" }

[dependencies]
rand = "0.7.0"
serde = "1.0.99"
serde_json = "1.0.40"
reqwest = "0.9.20"