name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
    - uses: actions/checkout@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install
      run: rustup update && rustup component add clippy && pip3 install -U pip setuptools && pip3 install -r requirements.txt
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test -- --test-threads 1 --verbose
    - name: Check format
      run: cargo fmt -- --check
